language: generic

sudo: required

services:
  - docker

script:
  - "docker-compose build"
  - "docker-compose run --rm --entrypoint nginx fsm -v"

notifications:
  email:
    - collins.christopher@gmail.com
