language: generic

sudo: required

services:
  - docker

script:
  - "docker-compose build"
  - "docker-compose run --rm --entrypoint nginx fsm -v"
  - "docker-compose run --rm --entrypoint ls fsm /var/www/fsm"

notifications:
  email:
    - collins.christopher@gmail.com
